### ISSUE TITLE
Top Tweets and Dates (Since, Until)

### ISSUE THREAD

**Issue by slarrain** [tomkdickinson/Twitter-Search-API-Python#2]
Hi,

First of all, I would like to thank you very much for writing this and not only that but coding it also in Python besides Java.

Second, I was wondering how do you incorporate dates in the query? I've been trying to add it in the query as it is in the web search but I haven't got the correct results. Should I use a specific format?

And third, I noticed that it is returning the Top Tweets and not all tweets. I think this is something you addressed on the Java version but it is still happening here. Should I change something in order to get all the tweets?

Thank you again.

**Comment by slarrain** [comment]
Ok, so I think the "Live" Tweets instead of the "Top" is fixed by changing "t" key in 'params' in the construct_url function to an "f'.
So this should fix it:
        params = {
            # Query Param
            'q': query,
            # Type Param
            'f': 'tweets'
        }

Although I haven't tested it enough.

**Comment by tomkdickinson** [comment]
Yep, that looks right. Checking out the AJAX call on Twitter has f as "tweets", and if it's missing it defaults to top tweets. I'll test that in a bit and push if it all works.

As for time, the query should be something like:

since:2015-10-01 until:2015-10-21

(Since 1st October, 2015, to 21st October, 2015)

However, you have to supply some form of text query with it as I've noticed just supplying the dates returns nothing. I assume this is because Twitters architecture takes a text query first to search, then facets the search with the dates.

**Comment by slarrain** [comment]
Yes, you are absolutely right. Let me thank you again for this great code.
